/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fupunb.numerador_FUP.TelasDeInteracao;

import br.com.fupunb.numerador_FUP.Classes.Documento;
import br.com.fupunb.numerador_FUP.Classes.Servidor;
import br.com.fupunb.numerador_FUP.Conexao_BD.Conecta_MySql;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marcio
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ImageIcon icon = new ImageIcon(getClass().getResource("/br/com/fupunb/numerador_FUP/Imagens/numerologia-empresarial.jpg"));
        Image image = icon.getImage();
        jDPainel_AREA_TRABALHO = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image, 0, 0, getWidth(),getHeight(),this);

            }

        };
        jIlF_LOGIN = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_USUARIO_FUB = new javax.swing.JTextField();
        jPasswordF_SENHA = new javax.swing.JPasswordField();
        jB_INICIAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jB_CADASTAR = new javax.swing.JButton();
        jIF_SOLICITAR_NUMERO = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTF_TIPO_DOC = new javax.swing.JTextField();
        jTF_DATA_EMISSAO = new javax.swing.JTextField();
        jTF_USUARIO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_ASSUNTO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTF_DESTINATARIO = new javax.swing.JTextField();
        jBT_GERAR_NUMERO = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTF_NUMERO_GERADO = new javax.swing.JTextField();
        JBt_AVANCAR = new javax.swing.JButton();
        jTF_ID_SERV = new javax.swing.JTextField();
        jBt_VOLTAR = new javax.swing.JButton();
        JTF_REMETENTE = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_TIPO_DE_DOCUMENTO = new javax.swing.JMenu();
        jMI_FAZER_LOGIN = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMe_SELECIONAR_TIPO_DOC = new javax.swing.JMenu();
        jMI_CARTA = new javax.swing.JMenuItem();
        jMI_MEMORANDO = new javax.swing.JMenuItem();
        jMI_OFICIO = new javax.swing.JMenuItem();
        jMe_CONSULTAR = new javax.swing.JMenu();
        jMI_NUMEROS_GERADOS = new javax.swing.JMenuItem();
        jMI_INFORMACOES_NUMERAROR = new javax.swing.JMenuItem();
        JM_CADASTRAR = new javax.swing.JMenu();
        JMI_USUARIO = new javax.swing.JMenuItem();
        JMI_SEQ_NUMERACAO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUMERADOR DE DOCUMENTOS OFICIAIS");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jIlF_LOGIN.setTitle("IDENTIFICAÇÃO DO USUÁRIO");
        jIlF_LOGIN.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("MATRICULA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SENHA:");

        jB_INICIAR.setBackground(new java.awt.Color(255, 204, 0));
        jB_INICIAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_INICIAR.setForeground(new java.awt.Color(51, 153, 0));
        jB_INICIAR.setText("INICIAR SOLICITAÇÃO");
        jB_INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_INICIARActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("PRIMEIRO ACESSO?  CLIQUE EM:");

        jB_CADASTAR.setBackground(new java.awt.Color(0, 255, 204));
        jB_CADASTAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_CADASTAR.setText("CADASTAR SENHA");
        jB_CADASTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CADASTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jIlF_LOGINLayout = new javax.swing.GroupLayout(jIlF_LOGIN.getContentPane());
        jIlF_LOGIN.getContentPane().setLayout(jIlF_LOGINLayout);
        jIlF_LOGINLayout.setHorizontalGroup(
            jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIlF_LOGINLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIlF_LOGINLayout.createSequentialGroup()
                        .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordF_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_USUARIO_FUB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jIlF_LOGINLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jB_CADASTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_INICIAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jIlF_LOGINLayout.setVerticalGroup(
            jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIlF_LOGINLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_USUARIO_FUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordF_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_INICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jIlF_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_CADASTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jIF_SOLICITAR_NUMERO.setTitle("SOLICITAR NÚMERO PARA DOCUMENTO");
        jIF_SOLICITAR_NUMERO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jIF_SOLICITAR_NUMERO.setPreferredSize(new java.awt.Dimension(810, 500));
        jIF_SOLICITAR_NUMERO.setVerifyInputWhenFocusTarget(false);
        jIF_SOLICITAR_NUMERO.setVisible(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SELECIONE O TIPO DE DOCUMENTO , INSIRA OS DADOS SOLICITADOS E DEPOIS CLIQUE NO BOTÃO 'GERAR NÚMERO.'");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("USUÁRIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("DATA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("TIPO DE DOCUMENTO");

        jTF_TIPO_DOC.setBackground(new java.awt.Color(204, 204, 0));
        jTF_TIPO_DOC.setForeground(new java.awt.Color(0, 0, 102));

        jTF_DATA_EMISSAO.setBackground(new java.awt.Color(204, 204, 0));
        jTF_DATA_EMISSAO.setForeground(new java.awt.Color(0, 0, 102));

        jTF_USUARIO.setBackground(new java.awt.Color(204, 204, 0));
        jTF_USUARIO.setForeground(new java.awt.Color(0, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("ASSUNTO:");

        jTF_ASSUNTO.setBackground(new java.awt.Color(204, 204, 0));
        jTF_ASSUNTO.setForeground(new java.awt.Color(0, 0, 102));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("REMETENTE: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("DESTINATÁRIO:");

        jTF_DESTINATARIO.setBackground(new java.awt.Color(204, 204, 0));
        jTF_DESTINATARIO.setForeground(new java.awt.Color(0, 0, 102));

        jBT_GERAR_NUMERO.setBackground(new java.awt.Color(255, 255, 0));
        jBT_GERAR_NUMERO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBT_GERAR_NUMERO.setForeground(new java.awt.Color(255, 0, 0));
        jBT_GERAR_NUMERO.setText("GERAR NÚMERO");
        jBT_GERAR_NUMERO.setBorder(new javax.swing.border.MatteBorder(null));
        jBT_GERAR_NUMERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_GERAR_NUMEROActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("NÚMERO GERADO: ");

        jTF_NUMERO_GERADO.setBackground(new java.awt.Color(204, 204, 0));
        jTF_NUMERO_GERADO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTF_NUMERO_GERADO.setForeground(new java.awt.Color(204, 0, 0));
        jTF_NUMERO_GERADO.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JBt_AVANCAR.setBackground(new java.awt.Color(255, 255, 255));
        JBt_AVANCAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBt_AVANCAR.setForeground(new java.awt.Color(51, 153, 0));
        JBt_AVANCAR.setText("AVANÇAR >>");
        JBt_AVANCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBt_AVANCARActionPerformed(evt);
            }
        });

        jBt_VOLTAR.setBackground(new java.awt.Color(255, 255, 255));
        jBt_VOLTAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBt_VOLTAR.setText("<< VOLTAR");
        jBt_VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_VOLTARActionPerformed(evt);
            }
        });

        JTF_REMETENTE.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jIF_SOLICITAR_NUMEROLayout = new javax.swing.GroupLayout(jIF_SOLICITAR_NUMERO.getContentPane());
        jIF_SOLICITAR_NUMERO.getContentPane().setLayout(jIF_SOLICITAR_NUMEROLayout);
        jIF_SOLICITAR_NUMEROLayout.setHorizontalGroup(
            jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                        .addComponent(jBT_GERAR_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_NUMERO_GERADO, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                        .addComponent(jTF_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_DATA_EMISSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_TIPO_DOC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTF_ASSUNTO)
                    .addComponent(jTF_DESTINATARIO)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                        .addComponent(jBt_VOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBt_AVANCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTF_REMETENTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_ID_SERV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jIF_SOLICITAR_NUMEROLayout.setVerticalGroup(
            jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIF_SOLICITAR_NUMEROLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_ID_SERV, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTF_DATA_EMISSAO)
                    .addComponent(jTF_USUARIO)
                    .addComponent(jTF_TIPO_DOC))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_ASSUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTF_REMETENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_DESTINATARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBt_AVANCAR)
                    .addComponent(jBt_VOLTAR))
                .addGap(45, 45, 45)
                .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jIF_SOLICITAR_NUMEROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTF_NUMERO_GERADO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBT_GERAR_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jDPainel_AREA_TRABALHO.setBackground(Color.lightGray);

        jDPainel_AREA_TRABALHO.setLayer(jIlF_LOGIN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPainel_AREA_TRABALHO.setLayer(jIF_SOLICITAR_NUMERO, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPainel_AREA_TRABALHOLayout = new javax.swing.GroupLayout(jDPainel_AREA_TRABALHO);
        jDPainel_AREA_TRABALHO.setLayout(jDPainel_AREA_TRABALHOLayout);
        jDPainel_AREA_TRABALHOLayout.setHorizontalGroup(
            jDPainel_AREA_TRABALHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPainel_AREA_TRABALHOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIlF_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jIF_SOLICITAR_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDPainel_AREA_TRABALHOLayout.setVerticalGroup(
            jDPainel_AREA_TRABALHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPainel_AREA_TRABALHOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDPainel_AREA_TRABALHOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIF_SOLICITAR_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIlF_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jDPainel_AREA_TRABALHO.setForeground(Color.lightGray);
        jDPainel_AREA_TRABALHO.setEnabled(false);

        jScrollPane2.setViewportView(jDPainel_AREA_TRABALHO);
        jScrollPane2.setBackground(Color.lightGray);
        jScrollPane2.setForeground(Color.lightGray);

        jM_TIPO_DE_DOCUMENTO.setBackground(new java.awt.Color(255, 255, 0));
        jM_TIPO_DE_DOCUMENTO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jM_TIPO_DE_DOCUMENTO.setForeground(new java.awt.Color(0, 51, 204));
        jM_TIPO_DE_DOCUMENTO.setText("SELECIONAR TIPO DE DOCUMENTO");
        jM_TIPO_DE_DOCUMENTO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMI_FAZER_LOGIN.setText("FAZER LOGIN");
        jMI_FAZER_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_FAZER_LOGINActionPerformed(evt);
            }
        });
        jM_TIPO_DE_DOCUMENTO.add(jMI_FAZER_LOGIN);
        jM_TIPO_DE_DOCUMENTO.add(jSeparator1);

        jMe_SELECIONAR_TIPO_DOC.setText("SELECIONE O TIPO DE DOCUMENTO");

        jMI_CARTA.setText("CARTA");
        jMI_CARTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_CARTAActionPerformed(evt);
            }
        });
        jMe_SELECIONAR_TIPO_DOC.add(jMI_CARTA);

        jMI_MEMORANDO.setText("MEMORANDO");
        jMI_MEMORANDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_MEMORANDOActionPerformed(evt);
            }
        });
        jMe_SELECIONAR_TIPO_DOC.add(jMI_MEMORANDO);

        jMI_OFICIO.setText("OFÍCIO");
        jMI_OFICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_OFICIOActionPerformed(evt);
            }
        });
        jMe_SELECIONAR_TIPO_DOC.add(jMI_OFICIO);

        jM_TIPO_DE_DOCUMENTO.add(jMe_SELECIONAR_TIPO_DOC);

        jMenuBar1.add(jM_TIPO_DE_DOCUMENTO);

        jMe_CONSULTAR.setForeground(new java.awt.Color(153, 0, 51));
        jMe_CONSULTAR.setText("CONSULTAR ");
        jMe_CONSULTAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMI_NUMEROS_GERADOS.setText("NÚMEROS GERADOS");
        jMI_NUMEROS_GERADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_NUMEROS_GERADOSActionPerformed(evt);
            }
        });
        jMe_CONSULTAR.add(jMI_NUMEROS_GERADOS);

        jMI_INFORMACOES_NUMERAROR.setText("INFORMAÇÕES SOBRE O NUMERADOR");
        jMI_INFORMACOES_NUMERAROR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_INFORMACOES_NUMERARORActionPerformed(evt);
            }
        });
        jMe_CONSULTAR.add(jMI_INFORMACOES_NUMERAROR);

        jMenuBar1.add(jMe_CONSULTAR);

        JM_CADASTRAR.setForeground(new java.awt.Color(0, 153, 153));
        JM_CADASTRAR.setText("CADASTRAR");
        JM_CADASTRAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JMI_USUARIO.setText("USUÁRIO");
        JMI_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_USUARIOActionPerformed(evt);
            }
        });
        JM_CADASTRAR.add(JMI_USUARIO);

        JMI_SEQ_NUMERACAO.setText("SEQUÊNCIA DE NUMERAÇÃO");
        JMI_SEQ_NUMERACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SEQ_NUMERACAOActionPerformed(evt);
            }
        });
        JM_CADASTRAR.add(JMI_SEQ_NUMERACAO);

        jMenuBar1.add(JM_CADASTRAR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_INICIARActionPerformed

        if (jPasswordF_SENHA.getText().equals("1X2Y3Z") && jTF_USUARIO_FUB.getText().equals("ADMIN")) {
            JM_CADASTRAR.setVisible(true);
        }
        botaoIniciarSolicitacao();

    }//GEN-LAST:event_jB_INICIARActionPerformed

    private void jB_CADASTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CADASTARActionPerformed

        chamarTelaDeCadastroDeSenha();
    }//GEN-LAST:event_jB_CADASTARActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        desabilitaMenus();
        jIF_SOLICITAR_NUMERO.setVisible(false);
        JM_CADASTRAR.setVisible(false);
       // jLabel3.setVisible(false);
       // jB_CADASTAR.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jMI_FAZER_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_FAZER_LOGINActionPerformed

        exibirLogin();
    }//GEN-LAST:event_jMI_FAZER_LOGINActionPerformed

    private void jMI_CARTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_CARTAActionPerformed

        selecionarTipoDocumento(1);//carta = 1
        jLabel11.setVisible(false);
        jTF_NUMERO_GERADO.setVisible(false);
    }//GEN-LAST:event_jMI_CARTAActionPerformed

    private void JBt_AVANCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBt_AVANCARActionPerformed

        botaoAvancarTelaQuadroSolicitarNumero();
    }//GEN-LAST:event_JBt_AVANCARActionPerformed

    private void jBT_GERAR_NUMEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_GERAR_NUMEROActionPerformed

        botaoGerarNumeroTelaQuadroSolicitarNumero();
    }//GEN-LAST:event_jBT_GERAR_NUMEROActionPerformed

    private void jBt_VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_VOLTARActionPerformed

        botaoVoltarTelaQuadroSolicitarNumero();
    }//GEN-LAST:event_jBt_VOLTARActionPerformed

    private void jMI_MEMORANDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_MEMORANDOActionPerformed

        selecionarTipoDocumento(2);//memorando = 2
        jLabel11.setVisible(false);
        jTF_NUMERO_GERADO.setVisible(false);
    }//GEN-LAST:event_jMI_MEMORANDOActionPerformed

    private void jMI_OFICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_OFICIOActionPerformed

        selecionarTipoDocumento(3);//oficio  = 3
        jLabel11.setVisible(false);
        jTF_NUMERO_GERADO.setVisible(false);
    }//GEN-LAST:event_jMI_OFICIOActionPerformed

    private void jMI_NUMEROS_GERADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_NUMEROS_GERADOSActionPerformed
        Tela_Consultar consultarSolicitacoes = new Tela_Consultar();
        jDPainel_AREA_TRABALHO.add(consultarSolicitacoes);
        consultarSolicitacoes.setVisible(true);
        try {
            consultarSolicitacoes.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }

    }//GEN-LAST:event_jMI_NUMEROS_GERADOSActionPerformed

    private void jMI_INFORMACOES_NUMERARORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_INFORMACOES_NUMERARORActionPerformed

       JOptionPane.showMessageDialog(null,"PARA GERAR NÚMEROS DE DOCUMENTOS OFÍCIAIS:\n\n"
                + "1 - APÓS FAZER LOGIN, ACESSE O MENU 'SELECIONAR TIPO DE DOCUMENTO'.\n"
                + "2 - CLIQUE NO SUBMENU 'SELECIONE O TIPO DE DOCUMENTO >'.\n"
                + "3 - SELECIONE UMA DAS OPÇÕES DISPONÍVEIS ('CARTA', 'MEMORANDO' OU 'OFÍCIO').\n"
                + "4 - NA TELA QUE ESTARÁ EM EXIBIÇÃO, CONFIRA SE O 'TIPO DE DOCUMENTO' SELECIONADO ESTÁ CORRETO,"
                + "\nPREENCHA OS CAMPOS 'ASSUNTO', "
                + "SELECIONE UMA OPÇÃO DE 'REMETENTE' E PREENCHA O CAMPO 'DESTINATÁRIO'."
                + "\nO PREENCHIMENTO DESSES CAMPOS É OBRIGATÓRIO.\n"
                + "5 - CONFIRA SE OS DADOS PREENCHIDOS ESTÃO TODOS CORRETOS E CLIQUE NO BOTÃO 'AVANÇAR>>'.\n"
                + "6 - CASO SEJA NECESSÁRIO FAZER ALGUMA ALTERAÇÃO APÓS TER CLICADO PARA AVANÇAR"
                + "\nCLIQUE NO BOTÃO 'VOLTAR>>'.\n"
                + "7 - ESTANDO TUDO PREENCHIDO CORRETAMENTE, CLIQUE NO BOTÃO AMARELO: 'GERAR NÚMERO'.\n"
                + "8 - AGUARDE ALGUNS INSTANTES E O NÚMERO GERADO SERÁ EXIBIDO NA TELA"
                + "\n\n\nCRÉTIDOS DA IMAGEM DE FUNDO NA TELA INICIAL: \n"
                + "http://marcusmarques.com.br/estrategias-de-negocio/"
                + "\nnumerologia-empresarial-influencia-dos-numeros-para-o-sucesso-dos-negocios"
                + "\n\nESSE PROGRAMA FOI DESENVOLVIDO POR MÁRCIO CRISTÓVÃO, ESTUDANDE DE PROGRAMAÇÃO NA UNIVERSIDADE ESTADUAL DE GOIÁS"
                + "\nE SERVIDOR TÉCNICO-ADMINISTRATIVO NA UnB / FUP",
                "INFORMAÇÕES SOBRE O NÚMERADOR DE DOCUMENTOS DA FUP:", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jMI_INFORMACOES_NUMERARORActionPerformed

    private void JMI_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_USUARIOActionPerformed

        Tela_Cadastrar_Usuario mostrarTela = new Tela_Cadastrar_Usuario();
        jDPainel_AREA_TRABALHO.add(mostrarTela);
        mostrarTela.setVisible(true);
        mostrarTela.setPosicao();

    }//GEN-LAST:event_JMI_USUARIOActionPerformed

    private void JMI_SEQ_NUMERACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SEQ_NUMERACAOActionPerformed
        Tela_Alterar_Numeracao chamarTelaAlteracao = new Tela_Alterar_Numeracao();
        jDPainel_AREA_TRABALHO.add(chamarTelaAlteracao);
        chamarTelaAlteracao.setVisible(true);
        chamarTelaAlteracao.setPosicao();
    }//GEN-LAST:event_JMI_SEQ_NUMERACAOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //metodo para inciar e verificar se está atualizado
        iniciarNumerador();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBt_AVANCAR;
    private javax.swing.JMenuItem JMI_SEQ_NUMERACAO;
    private javax.swing.JMenuItem JMI_USUARIO;
    private javax.swing.JMenu JM_CADASTRAR;
    private javax.swing.JTextField JTF_REMETENTE;
    private javax.swing.JButton jBT_GERAR_NUMERO;
    private javax.swing.JButton jB_CADASTAR;
    private javax.swing.JButton jB_INICIAR;
    private javax.swing.JButton jBt_VOLTAR;
    private javax.swing.JDesktopPane jDPainel_AREA_TRABALHO;
    private javax.swing.JInternalFrame jIF_SOLICITAR_NUMERO;
    private javax.swing.JInternalFrame jIlF_LOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMI_CARTA;
    private javax.swing.JMenuItem jMI_FAZER_LOGIN;
    private javax.swing.JMenuItem jMI_INFORMACOES_NUMERAROR;
    private javax.swing.JMenuItem jMI_MEMORANDO;
    private javax.swing.JMenuItem jMI_NUMEROS_GERADOS;
    private javax.swing.JMenuItem jMI_OFICIO;
    private javax.swing.JMenu jM_TIPO_DE_DOCUMENTO;
    private javax.swing.JMenu jMe_CONSULTAR;
    private javax.swing.JMenu jMe_SELECIONAR_TIPO_DOC;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordF_SENHA;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTF_ASSUNTO;
    private javax.swing.JTextField jTF_DATA_EMISSAO;
    private javax.swing.JTextField jTF_DESTINATARIO;
    private javax.swing.JTextField jTF_ID_SERV;
    private javax.swing.JTextField jTF_NUMERO_GERADO;
    private javax.swing.JTextField jTF_TIPO_DOC;
    private javax.swing.JTextField jTF_USUARIO;
    private javax.swing.JTextField jTF_USUARIO_FUB;
    // End of variables declaration//GEN-END:variables

    //metodo para abrir numerador e verificar se o mesmo está atualizado
    public static void iniciarNumerador() {

        Documento verificarAnoVigente = new Documento();

        try {
            if (verificarAnoVigente.consultarAnoVigente()) {
                System.out.println("A numeração não precisa ser reiniciada.");

            } else {
                verificarAnoVigente.zerarNumeracao("CARTA", "REINICIANDO CONTAGEM DEVIDO A VIRADA DE ANO", 0);
                verificarAnoVigente.zerarNumeracao("MEMORANDO", "REINICIANDO CONTAGEM DEVIDO A VIRADA DE ANO", 0);
                verificarAnoVigente.zerarNumeracao("OFÍCIO", "REINICIANDO CONTAGEM DEVIDO A VIRADA DE ANO", 0);
                JOptionPane.showMessageDialog(null, "DEVIDO A MUDANÇA DE ANO A NUMERÇÃO FOI REINICIADA.");
            }

        } catch (IOException | SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL INICIAR O NÚMERADOR. TENTE NOVAMENTE MAIS TARDE!",
                    "FALHA NA CONEXÃO COM A BASE DE DADOS", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

    }

    //métdodos da tela de LOGIN
    public void chamarTelaDeCadastroDeSenha() {

        Tela_Cadastrar_Senha cadastro = new Tela_Cadastrar_Senha();
        jDPainel_AREA_TRABALHO.add(cadastro);
        JOptionPane.showMessageDialog(null, "INFORME SUA MATRICULA E CLIQUE NO BOTÃO 'AVANÇAR>>'");
        cadastro.setVisible(true);
        // cadastro.setPosicao();
        jIlF_LOGIN.setVisible(false);

    }

    public void exibirLogin() {

        if (jIlF_LOGIN.isVisible()) {

        } else {
            jIlF_LOGIN.setVisible(true);
            jB_CADASTAR.setEnabled(false);
        }

    }

    public void desabilitaMenus() {

        jMe_SELECIONAR_TIPO_DOC.setEnabled(false);
        jMI_NUMEROS_GERADOS.setEnabled(false);
    }

    public void habilitarMenus() {

        jMe_SELECIONAR_TIPO_DOC.setEnabled(true);
        jMe_CONSULTAR.setEnabled(true);
        jMI_NUMEROS_GERADOS.setEnabled(true);
    }

    public void botaoIniciarSolicitacao() {

        Servidor validarLogin = new Servidor();

        try {
            if (("".equalsIgnoreCase(jTF_USUARIO_FUB.getText())) && ("".equalsIgnoreCase(jPasswordF_SENHA.getText()))) {

            } else {
                conferindoStatusSenha(jTF_USUARIO_FUB.getText());
            }
        } catch (SQLException | IOException ex) {
            System.out.println(ex);
        }//Verificar se os campos não estão em branco para não cadastrar em branco
        if (("".equalsIgnoreCase(jTF_USUARIO_FUB.getText())) && ("".equalsIgnoreCase(jPasswordF_SENHA.getText()))) {

        } else {
            try {

                if (validarLogin.verificarAcessoUsuario(jTF_USUARIO_FUB.getText(), jPasswordF_SENHA.getText())) {
                    JOptionPane.showMessageDialog(null, "ACESSE O MENU 'SELECIONAR TIPO DE DOCUMENTO'.");

                    chamarQuadroSolicitarNumeroDocumento();

                    jMI_FAZER_LOGIN.setEnabled(false);
                    jPasswordF_SENHA.setText("");
                    jTF_USUARIO_FUB.setText("");
                    jIlF_LOGIN.setVisible(false);
                    habilitarMenus();
                } else {
                    JOptionPane.showMessageDialog(null, "SENHA OU MATRICULA INCORRETA!");
                    jPasswordF_SENHA.setText("");
                    jTF_USUARIO_FUB.setText("");
                    jTF_USUARIO_FUB.requestFocus();
                }
            } catch (IOException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL ACESSAR A BASE DE DADOS!");
                System.out.println(ex);
            }
        }

    }//esse botão confere se a senha está correta

    public void conferindoStatusSenha(String matricula) throws SQLException, IOException {

        Servidor manipularStatusSenha = new Servidor();
        manipularStatusSenha.setMatriculaFUB(matricula);
        String buscarInformacoesStatus = "SELECT STATUSSENHA FROM servidor WHERE MATRICULAFUB = ?";
        Connection conexao = Conecta_MySql.conectarDB();
        try {

            PreparedStatement verificarStatus = conexao.prepareStatement(buscarInformacoesStatus);
            verificarStatus.setString(1, manipularStatusSenha.getMatriculaFUB());
            ResultSet rs = verificarStatus.executeQuery();
            boolean statusOK = false;
            while (rs.next()) {

                statusOK = manipularStatusSenha.verificarStatusSenha(rs.getInt("STATUSSENHA"));
            }
            if (statusOK) {

            } else {
                JOptionPane.showMessageDialog(null, "VOCÊ AINDA NÃO POSSUI SENHA CADASTRADA! CLIQUE EM 'CADASTRAR-SE'.");
                jTF_USUARIO_FUB.setText("");
                jPasswordF_SENHA.setText("");
                jTF_USUARIO_FUB.requestFocus();

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL ACESSAR A BASE DE DADOS!\n"
                    + "VERIFIQUE SE OS DADOS DE IDENTIFICAÇÃO ESTÃO CORRETOS.");
            System.out.println(ex);
        } finally {
            if (conexao != null) {
                conexao.close();
                System.out.println("Banco desconectado");
            }
        }

    }

    //---------------------------------------------------------------------------------------------------//
    //métodos da Tela Solicitar Número
    public void desabilitarCamposTelaSolicitarNumero() {

        jTF_USUARIO.setEnabled(false);
        jTF_DATA_EMISSAO.setEnabled(false);
        jTF_TIPO_DOC.setEnabled(false);
        jTF_ASSUNTO.setEnabled(false);
        jTF_DESTINATARIO.setEnabled(false);
        JTF_REMETENTE.setEnabled(false);
        JBt_AVANCAR.setEnabled(false);
        jBt_VOLTAR.setEnabled(false);

    }

    public void habilitarCamposTelaSolicitarNumero() {

        jTF_ASSUNTO.setEnabled(true);
        jTF_DESTINATARIO.setEnabled(true);
        JTF_REMETENTE.setEnabled(true);
        JBt_AVANCAR.setEnabled(true);
        jBt_VOLTAR.setEnabled(true);

    }

    public void limparCamposObrigatorios() {

        jTF_ASSUNTO.setText("");
        jTF_DESTINATARIO.setText("");
        JTF_REMETENTE.setText("");
    }

    public void botaoAvancarTelaQuadroSolicitarNumero() {

        if ("".equals(jTF_ASSUNTO.getText()) || "".equals(jTF_DESTINATARIO.getText()) || "".equals(JTF_REMETENTE.getText())) {
            JOptionPane.showMessageDialog(null, "ALGUM DOS SEGUINTES CAMPOS NÃO FOI PREENCHIDO: \n'ASSUNTO'\n'REMETENTE'\n'DESTINATÁRIO'");
        } else {
            jBT_GERAR_NUMERO.setVisible(true);
            desabilitarCamposTelaSolicitarNumero();
            jBt_VOLTAR.setEnabled(true);
            JOptionPane.showMessageDialog(null, "CONFIRA SE OS CAMPOS FORAM PREENCHIDOS CORRETAMENTE E CLIQUE NO BOTÃO "
                    + "'GERAR NÚMERO'.\nCASO NÃO ESTEJAM CORRETOS, CLIQUE EM '<< VOLTAR'");
            // jLabel11.setVisible(true);
            // jTF_NUMERO_GERADO.setVisible(true);
        }
    }

    public void botaoVoltarTelaQuadroSolicitarNumero() {
        jTF_ASSUNTO.setEnabled(true);
        jTF_DESTINATARIO.setEnabled(true);
        JTF_REMETENTE.setEnabled(true);
        jBT_GERAR_NUMERO.setVisible(false);
        JBt_AVANCAR.setEnabled(true);
        JOptionPane.showMessageDialog(null, "PARA ALTERAR O TIPO DE DOCUMENTO ACESSE O MENU: "
                + " 'SELECIONAR TIPO DE DOCUMENTO'.");

    }

    public void botaoGerarNumeroTelaQuadroSolicitarNumero() {

        jBT_GERAR_NUMERO.setVisible(false);
        desabilitarCamposTelaSolicitarNumero();
        jLabel11.setVisible(true);
        jTF_NUMERO_GERADO.setVisible(true);
        Documento gerarNumero = new Documento();
        gerarNumero.setNomeDOC(jTF_TIPO_DOC.getText());
        try {

            int numeroSemFormatar = gerarNumero.numeroSemFormatar(gerarNumero.buscarNumeroAnteriorBancoDados(gerarNumero.getNomeDOC()));

            jTF_NUMERO_GERADO.setText(gerarNumero.numerarDoc(gerarNumero.buscarNumeroAnteriorBancoDados(gerarNumero.getNomeDOC())));

            int idUser = Integer.valueOf(jTF_ID_SERV.getText());

            String anovigente = gerarNumero.anoVigente();

            gerarNumero.inserirSolicitacaoBancoDados(idUser, numeroSemFormatar, jTF_NUMERO_GERADO.getText(),
                    jTF_TIPO_DOC.getText(), jTF_ASSUNTO.getText(), (String) JTF_REMETENTE.getText(),
                    jTF_DESTINATARIO.getText(), jTF_DATA_EMISSAO.getText(), anovigente);

         //TRECHO RETIRADO ATÉ SOLUCIONAR PROBLEMA DO ENVIO DE E-MAIL
            /*  if (jTF_USUARIO.getText().equals("ADMINISTRADOR")) {

            } else {
                int resposta = JOptionPane.showConfirmDialog(null, String.format("DESEJA QUE O NÚMERO SEJA ENVIADO PARA "
                        + "O E-MAIL: " + buscandoEmailUsuario(idUser) + " ?"));
                switch (resposta) {

                    case 0:
                        enviarEmailNumero();
                        break;
                    case 1:
                        break;
                    case 2:
                        break;
                }
            }*/

            limparCamposObrigatorios();
            jTF_TIPO_DOC.setText("");
        } catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO NO ENVIO DO EMAIL" + ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO NO ENVIO DO EMAIL" + ex);
        }

    }

    public void enviarEmailNumero() throws IOException, SQLException {

        Documento gerarNumero = new Documento();
        int idUser = Integer.valueOf(jTF_ID_SERV.getText());
        gerarNumero.enviarEmailComNumeroGerado(buscandoEmailUsuario(idUser), jTF_USUARIO.getText(),
                jTF_TIPO_DOC.getText(),
                jTF_NUMERO_GERADO.getText(), jTF_ASSUNTO.getText(),
                (String) JTF_REMETENTE.getText(), jTF_DESTINATARIO.getText());

    }

    public void chamarQuadroSolicitarNumeroDocumento() {

        Documento dataEmissaoSetarID = new Documento();
        try {
            jIF_SOLICITAR_NUMERO.setVisible(true);
            jTF_USUARIO.setText(buscandoNomeUsuario(jTF_USUARIO_FUB.getText()));
            jTF_DATA_EMISSAO.setText(dataEmissaoSetarID.datarEmissao());
            desabilitarCamposTelaSolicitarNumero();
            jTF_ID_SERV.setText(String.valueOf(buscandoId_servUsuario(jTF_USUARIO_FUB.getText())));
            jTF_ID_SERV.setVisible(false);
            jBT_GERAR_NUMERO.setVisible(false);
            jLabel11.setVisible(false);
            jTF_NUMERO_GERADO.setVisible(false);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //  JOptionPane.showMessageDialog(null, jTF_ID_SERV.getText());
    }

    public void selecionarTipoDocumento(int tipo) {

        jTF_NUMERO_GERADO.setText("");
        if (!"".equals(jTF_TIPO_DOC.getText())) {
            int resposta = JOptionPane.showConfirmDialog(null, String.format("JÁ EXISTE UMA SOLICITAÇÃO DE (" + jTF_TIPO_DOC.getText() + ") "
                    + "EM ANDAMENTO. DESEJA DESCARTÁ-LA?"));
            switch (resposta) {

                case 0:
                    habilitarCamposTelaSolicitarNumero();
                    Documento carta = new Documento();
                    jTF_TIPO_DOC.setText(carta.nomearTipo(tipo));
                    limparCamposObrigatorios();
                    jBT_GERAR_NUMERO.setVisible(false);
                    JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS: \n'ASSUNTO'\n'REMETENTE'\n'DESTINATÁRIO'"
                            + "\nDEPOIS CLIQUE EM 'AVANÇAR >>'");
                    break;
                case 1:
                    break;
                case 2:
                    break;
            }

        } else {
            habilitarCamposTelaSolicitarNumero();
            Documento carta = new Documento();
            jTF_TIPO_DOC.setText(carta.nomearTipo(tipo));
            JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS: \n'ASSUNTO'\n'REMETENTE'\n'DESTINATÁRIO'"
                    + "\nDEPOIS CLIQUE EM 'AVANÇAR >>'");
        }

    }

    //métodos com retorno (Tela Solicitar Número)
    public String buscandoNomeUsuario(String MatriculaUsuario) throws IOException, SQLException {

        Servidor buscarNome = new Servidor();
        buscarNome.setMatriculaFUB(MatriculaUsuario);
        String buscarInformacoes = "SELECT NOME FROM servidor WHERE MATRICULAFUB = ?";
        String nomeUsuario = "";
        Connection conexao = Conecta_MySql.conectarDB();
        try {
            PreparedStatement nome = conexao.prepareStatement(buscarInformacoes);
            nome.setString(1, buscarNome.getMatriculaFUB());
            ResultSet rs = nome.executeQuery();
            while (rs.next()) {
                nomeUsuario = rs.getString("NOME");
            }
        } finally {
            if (conexao != null) {
                conexao.close();
                System.out.println("Banco desconectado");
            }
        }
        return nomeUsuario;
    }

    public int buscandoId_servUsuario(String MatriculaUsuario) throws IOException, SQLException {

        Servidor buscarIdServ = new Servidor();
        buscarIdServ.setMatriculaFUB(MatriculaUsuario);
        String buscarInformacoes = "SELECT id_serv FROM servidor WHERE MATRICULAFUB = ?";
        int idServ = 0;
        Connection conexao = Conecta_MySql.conectarDB();
        try {
            PreparedStatement nome = conexao.prepareStatement(buscarInformacoes);
            nome.setString(1, buscarIdServ.getMatriculaFUB());
            ResultSet rs = nome.executeQuery();
            while (rs.next()) {
                idServ = rs.getInt("id_serv");
            }
        } finally {
            if (conexao != null) {
                conexao.close();
                System.out.println("Banco desconectado");
            }
        }
        return idServ;
    }

    public String buscandoEmailUsuario(int id_serv) throws IOException, SQLException {

        Servidor buscarEmail = new Servidor();
        buscarEmail.setId_serv(id_serv);
        String buscarInformacoes = "SELECT EMAIL FROM servidor WHERE id_serv = ?";
        String email = "";
        Connection conexao = Conecta_MySql.conectarDB();
        try {
            PreparedStatement EMAIL = conexao.prepareStatement(buscarInformacoes);
            EMAIL.setInt(1, buscarEmail.getId_serv());
            ResultSet rs = EMAIL.executeQuery();
            while (rs.next()) {
                email = rs.getString("EMAIL");
            }
        } finally {
            if (conexao != null) {
                conexao.close();
                System.out.println("Banco desconectado");
            }
        }
        return email;

    }

}
