/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fupunb.numerador_FUP.TelasDeInteracao;

import br.com.fupunb.numerador_FUP.Classes.Documento;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author marcio
 */
public class Tela_Alterar_Numeracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Alterar_Numeracao
     */
    public Tela_Alterar_Numeracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JCBX_TIPOS_DOCS = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JTF_NOVO_NUMERO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBT_SALVAR = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("ALTERAR SEQUÊNCIA DO NUMERADOR");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SELECIONE PARA QUAL TIPO DE DOCUMENTO A NUMERAÇÃO DEVERÁ SER RENICIADA:");

        JCBX_TIPOS_DOCS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "CARTA", "MEMORANDO", "OFÍCIO" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("INFORME A PARTIR DE QUAL NÚMERO A NOVA SEQUÊNCIA DEVERÁ PROSSEGUIR:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("EX: SE VOCÊ COLOCAR O NÚMERO 10 (NÃO COLOCAR \"/ANO\"), O PRÓXIMO NÚMERO A SER GERADO SERÁ O NÚMERO 11. (0011 / ANO)");
        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        JBT_SALVAR.setBackground(new java.awt.Color(255, 255, 0));
        JBT_SALVAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBT_SALVAR.setForeground(new java.awt.Color(51, 153, 0));
        JBT_SALVAR.setText("SALVAR");
        JBT_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_SALVARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JBT_SALVAR))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTF_NOVO_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JCBX_TIPOS_DOCS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JCBX_TIPOS_DOCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_NOVO_NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBT_SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3AncestorAdded

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        String mensagem = "A NUMERAÇÃO É REINICIADA AUTOMATICAMENTE TODO DIA 01/01 DE CADA ANO.";
        String mensagem2 = "CASO DESEJE CONTINUAR A SEQUÊNCIA, ESSA DATA PRECISA SER OBSERVADA E O ÚLTIMO NÚMERO DA SEQÊNCIA VIGENTE REINSERIDO.";
        String mensagem3 = "CASO DESEJE QUE A SEQUÊNCIA SEJA INICIADA A PARTIR DE UM NÚMERO QUE NÃO SEJA 0001 / ANO,";
        String mensagem4 = "EX: 1001 / ANO. BASTA INSERIR O NÚMERO 1000 COMO ÚLTIMO NÚMERO. A SEQUÊNCIA DESSE NUMERADOR É LIMITADA A 9999 / ANO.";
        JOptionPane.showMessageDialog(null, mensagem + "\n" + mensagem2 + "\n" + mensagem3 + "\n" + mensagem4, "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_formInternalFrameOpened

    private void JBT_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_SALVARActionPerformed
        if (JCBX_TIPOS_DOCS.getSelectedItem().equals("Selecionar") || "".equals(JTF_NOVO_NUMERO.getText())) {
            JOptionPane.showMessageDialog(null, "SELECIONE UM TIPO DE DOCUMENTO E INSIRA UM VALOR PARA NOVA SEQUÊNCIA!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);

        } else {
            alterarNumeracaoUsuario();
            JCBX_TIPOS_DOCS.setSelectedItem("Selecionar");
            JTF_NOVO_NUMERO.setText("");
        }
    }//GEN-LAST:event_JBT_SALVARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_SALVAR;
    private javax.swing.JComboBox<String> JCBX_TIPOS_DOCS;
    private javax.swing.JTextField JTF_NOVO_NUMERO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void alterarNumeracaoUsuario() {

        Documento efetuandoAlteracao = new Documento();
        try {

            efetuandoAlteracao.zerarNumeracao(String.valueOf(JCBX_TIPOS_DOCS.getSelectedItem()),
                    "ALTERAÇÃO DE SEQUÊNCIA EFETUADA PELO USUÁRIO", Integer.valueOf(JTF_NOVO_NUMERO.getText()));
            JOptionPane.showMessageDialog(null, "SEQUÊNCIA ALTERADA COM SUCESSO!");
        } catch (SQLException | IOException ex) {
            System.out.println("ERRO: "+ex);
            JOptionPane.showMessageDialog(null, "NÃO FOI POSSIVEL EFETUAR A ALTERAÇÃO!", "ERRO!", JOptionPane.WARNING_MESSAGE);
        }
    }

}
