/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fupunb.numerador_FUP.TelasDeInteracao;

import br.com.fupunb.numerador_FUP.Classes.Servidor;
import br.com.fupunb.numerador_FUP.Conexao_BD.Conecta_MySql;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcio
 */
public class Tela_Cadastrar_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Cadastrar_Usuario
     */
    public Tela_Cadastrar_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_NOME = new javax.swing.JTextField();
        JTF_MATRICULA = new javax.swing.JTextField();
        JTF_EMAIL = new javax.swing.JTextField();
        JBT_SALVAR = new javax.swing.JButton();
        JBT_INCLUIR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELA_USUARIOS_CADASTRADOS = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel_ESCOLHA_SENHA = new javax.swing.JLabel();
        jPasswordF_ESCOLHER_SENHA = new javax.swing.JPasswordField();
        jB_CADASTRAR_SENHA = new javax.swing.JButton();
        JTF_ESPELHO_MATRICULA = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("CADASTRAR / ALTERAR USUÁRIO");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NOME:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MATRICULA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("E-MAIL: ");

        JBT_SALVAR.setBackground(new java.awt.Color(255, 255, 51));
        JBT_SALVAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBT_SALVAR.setForeground(new java.awt.Color(51, 102, 0));
        JBT_SALVAR.setText("SALVAR");
        JBT_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_SALVARActionPerformed(evt);
            }
        });

        JBT_INCLUIR.setBackground(new java.awt.Color(255, 255, 255));
        JBT_INCLUIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBT_INCLUIR.setForeground(new java.awt.Color(255, 0, 0));
        JBT_INCLUIR.setText("INCLUIR / ALTERAR");
        JBT_INCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_INCLUIRActionPerformed(evt);
            }
        });

        TABELA_USUARIOS_CADASTRADOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "MATRICULA", "E-MAIL"
            }
        ));
        jScrollPane1.setViewportView(TABELA_USUARIOS_CADASTRADOS);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USUÁRIOS CADASTRADOS");

        jLabel_ESCOLHA_SENHA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_ESCOLHA_SENHA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_ESCOLHA_SENHA.setText("CADASTRAR SENHA:");

        jB_CADASTRAR_SENHA.setBackground(new java.awt.Color(255, 255, 0));
        jB_CADASTRAR_SENHA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_CADASTRAR_SENHA.setForeground(new java.awt.Color(51, 102, 0));
        jB_CADASTRAR_SENHA.setText("CADASTRAR >>");
        jB_CADASTRAR_SENHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CADASTRAR_SENHAActionPerformed(evt);
            }
        });

        JTF_ESPELHO_MATRICULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ESPELHO_MATRICULAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTF_NOME, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addComponent(JTF_MATRICULA)
                                .addComponent(JTF_EMAIL))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBT_INCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBT_SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ESCOLHA_SENHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordF_ESCOLHER_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_CADASTRAR_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addComponent(JTF_ESPELHO_MATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_MATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_ESPELHO_MATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBT_INCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBT_SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ESCOLHA_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordF_ESCOLHER_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_CADASTRAR_SENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 566, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void JBT_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_SALVARActionPerformed
        Servidor cadastrarUsuario = new Servidor();
        cadastrarUsuario.setNome(JTF_NOME.getText());
        cadastrarUsuario.setMatriculaFUB(JTF_MATRICULA.getText());
        cadastrarUsuario.setEmail(JTF_EMAIL.getText());
        JTF_ESPELHO_MATRICULA.setText(cadastrarUsuario.getMatriculaFUB());

        if ("".equals(JTF_NOME.getText()) || "".equals(JTF_MATRICULA.getText()) || "".equals(JTF_EMAIL.getText())) {

            JOptionPane.showMessageDialog(null, "ALGUM DOS SEGUINTES CAMPOS NÃO FOI PREENCHIDO: "
                    + "\n'NOME'\n'MATRICULA'\n'E-MAIL'\n***ESSES CAMPOS SÃO OBRIGATÓRIOS.");
        } else {
            try {
                cadastrarUsuario.cadastroServidor(cadastrarUsuario.getNome(), cadastrarUsuario.getMatriculaFUB(), cadastrarUsuario.getEmail());
                limparTabela(TABELA_USUARIOS_CADASTRADOS);
                tabelaListarUsuarios(TABELA_USUARIOS_CADASTRADOS);
            } catch (IOException | SQLException ex) {
                Logger.getLogger(Tela_Cadastrar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            limparCampos();
            JBT_INCLUIR.setEnabled(true);
            JBT_SALVAR.setEnabled(false);
            jPasswordF_ESCOLHER_SENHA.setEnabled(true);
            jB_CADASTRAR_SENHA.setEnabled(true);
            desabilitarCampos();

        }
    }//GEN-LAST:event_JBT_SALVARActionPerformed

    private void JBT_INCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_INCLUIRActionPerformed
        habilitarCampos();
        JBT_INCLUIR.setEnabled(false);
        JBT_SALVAR.setEnabled(true);
        jPasswordF_ESCOLHER_SENHA.setEnabled(false);
        jB_CADASTRAR_SENHA.setEnabled(false);

    }//GEN-LAST:event_JBT_INCLUIRActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        try {
            desabilitarCampos();
            JTF_ESPELHO_MATRICULA.setVisible(false);
            JBT_SALVAR.setEnabled(false);
            jPasswordF_ESCOLHER_SENHA.setEnabled(false);
            jB_CADASTRAR_SENHA.setEnabled(false);
            tabelaListarUsuarios(TABELA_USUARIOS_CADASTRADOS);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastrar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formInternalFrameOpened

    private void jB_CADASTRAR_SENHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CADASTRAR_SENHAActionPerformed

        try {
            Servidor cadastroSenha = new Servidor();
            cadastroSenha.cadastrarSenha(jPasswordF_ESCOLHER_SENHA.getText(), JTF_ESPELHO_MATRICULA.getText());
            JTF_ESPELHO_MATRICULA.setText("");
            jPasswordF_ESCOLHER_SENHA.setText("");
            jPasswordF_ESCOLHER_SENHA.setEnabled(false);
            jB_CADASTRAR_SENHA.setEnabled(false);
            JOptionPane.showMessageDialog(null, "SENHA CADASTRADA COM SUCESSO!");
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastrar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Tela_Cadastrar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_CADASTRAR_SENHAActionPerformed

    private void JTF_ESPELHO_MATRICULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ESPELHO_MATRICULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ESPELHO_MATRICULAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_INCLUIR;
    private javax.swing.JButton JBT_SALVAR;
    private javax.swing.JTextField JTF_EMAIL;
    private javax.swing.JTextField JTF_ESPELHO_MATRICULA;
    private javax.swing.JTextField JTF_MATRICULA;
    private javax.swing.JTextField JTF_NOME;
    private javax.swing.JTable TABELA_USUARIOS_CADASTRADOS;
    private javax.swing.JButton jB_CADASTRAR_SENHA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_ESCOLHA_SENHA;
    private javax.swing.JPasswordField jPasswordF_ESCOLHER_SENHA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public void habilitarCampos() {

        JTF_NOME.setEnabled(true);
        JTF_MATRICULA.setEnabled(true);
        JTF_EMAIL.setEnabled(true);

    }

    public void desabilitarCampos() {

        JTF_NOME.setEnabled(false);
        JTF_MATRICULA.setEnabled(false);
        JTF_EMAIL.setEnabled(false);

    }

    public void limparCampos() {

        JTF_NOME.setText("");
        JTF_MATRICULA.setText("");
        JTF_EMAIL.setText("");

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void tabelaListarUsuarios(JTable tabela) throws SQLException {
        DefaultTableModel Tabela = (DefaultTableModel) tabela.getModel();
        Connection conexao = null;
        try {
            conexao = Conecta_MySql.conectarDB();
            PreparedStatement listarTabela = conexao.prepareStatement("SELECT NOME, MATRICULAFUB, EMAIL FROM servidor ORDER BY NOME");
            ResultSet rs = listarTabela.executeQuery();
            while (rs.next()) {
                if (rs.getString("NOME").equals("ADMINISTRADOR")) {

                } else {
                    Tabela.addRow(new String[]{rs.getString("NOME"), rs.getString("MATRICULAFUB"), rs.getString("EMAIL")});
                }
            }
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Tela_Cadastrar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (conexao != null) {
                conexao.close();
                System.out.println("Conexão finalizada!");
            }
        }

    }

    public void limparTabela(JTable tabela) {

        DefaultTableModel val = (DefaultTableModel) tabela.getModel();

        for (int i = tabela.getRowCount(); i >= 0; i--) {

            if (i > 0) {
                //JOptionPane.showMessageDialog(null, i);
                val.removeRow(0);

            }

        }
    }
}
